name: FormDSL
version: 1.0.1-SNAPSHOT
main: cn.lanink.formdsl.PluginMain
api: [1.0.11]
description: support dsl operation in kotlin to build Form UI
author: iGxnon
softdepend:
  - "FullKotlinLib"
depend:
  - "MemoriesOfTime-GameCore"

permissions:
  formdsl.ftest:
    default: op