name: FormDSL
version: 1.0.0-SNAPSHOT
main: cn.lanink.formdsl.PluginMain
api: [1.0.11]
description: supoort dsl operation in kotlin to build Form UI
author: iGxnon
softdepend:
  - "FullKotlinLib"
depend:
  - "MemoriesOfTime-GameCore"

commands:
  formtest:
    description: Test
    permission: formdsl.ftest
    usage: /formtest [type]

permissions:
  formdsl.ftest:
    default: op